name: Test

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: yarn install
        run: |
          yarn install --frozen-lockfile --network-timeout 300000

      - name: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This is used for APIs
          DEPLOY_SERVER_URL: ${{ secrets.DEPLOY_SERVER_URL }}
          REACT_TODO_API_IVO: ${{ secrets.REACT_TODO_API_IVO }}
          REACT_TODO_API_MARGI: ${{ secrets.REACT_TODO_API_MARGI }}
          REACT_APP_FORECAST_APP_ID: ${{ secrets.REACT_APP_FORECAST_APP_ID }}
        run: |
          echo "Hello $REACT_APP_FORECAST_APP_ID"
          yarn package
          yarn lint
          yarn tsc
          yarn test
